### ISSUE TITLE
Docker not building

### ISSUE THREAD

**Issue by ThomasWollmann** [bgruening/docker-jupyter-notebook#10]
> cabal: Error: some packages failed to install:
> ihaskell-0.8.0.0 depends on zeromq4-haskell-0.6.3 which failed to install.
> ipython-kernel-0.8.4.0 depends on zeromq4-haskell-0.6.3 which failed to
> install.
> zeromq4-haskell-0.6.3 failed during the configure step. The exception was:
> ExitFailure 1

I can't manage to build master with "docker build -t galaxy-jupyter-notebook . ". Container also fails on quay.io.

**Comment by bgruening** [comment]
Nice the new haskell needs some wired c-library that is not part of this base debian image. :(
