### ISSUE TITLE
Docker container fails to start

### ISSUE THREAD

**Issue by c-ruttkies** [bgruening/docker-jupyter-notebook#15]
Hi,

I tried to get the bgruening/docker-jupyter-notebook running by using the command you provided in the readme

```console
docker run -p 7777:8888 bgruening/docker-jupyter-notebook
```

This causes an exception:

```
[TrustNotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
Signing notebook: /import/ipython_galaxy_notebook.ipynb
[E 07:40:41.105 NotebookApp] Exception while loading config file /home/jovyan/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/traitlets/config/application.py", line 535, in _load_config_files
        config = loader.load_config()
      File "/opt/conda/lib/python3.4/site-packages/traitlets/config/loader.py", line 432, in load_config
        self._read_file_as_dict()
      File "/opt/conda/lib/python3.4/site-packages/traitlets/config/loader.py", line 464, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/opt/conda/lib/python3.4/site-packages/ipython_genutils/py3compat.py", line 185, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/home/jovyan/.jupyter/jupyter_notebook_config.py", line 20, in <module>
        """ % {'CORS_ORIGIN': os.environ['CORS_ORIGIN'], 'WS_CORS_ORIGIN': 'ws://%s' % os.environ['CORS_ORIGIN'].split('://')[1]}
    IndexError: list index out of range
[I 07:40:41.113 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 07:40:41.144 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 07:40:41.173 NotebookApp] Serving notebooks from local directory: /import
[I 07:40:41.174 NotebookApp] 0 active kernels 
[I 07:40:41.174 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 07:40:41.174 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

which seems to come from the /home/jovyan/.jupyter/jupyter_notebook_config.py in line 20 where it runs

```
""" % {'CORS_ORIGIN': os.environ['CORS_ORIGIN'], 'WS_CORS_ORIGIN': 'ws://%s' % os.environ['CORS_ORIGIN'].split('://')[1]}
```

I would assume the split function but my python experience is just sparse. 

The docker container is running after this exception but there is no service available on port 8888.

Maybe you have a quick fix for this problem.

Thanks in advance.

Best regards,
Christoph, @sneumann, @korseby

**Comment by bgruening** [comment]
Hi @c-ruttkies,

are you using this container from Galaxy or as a standalone container? It was not made for the latter case, Galaxy starts the container in a speical way to connect to it and it can very well be that this will not work. I never tested in a standalone case.

**Comment by c-ruttkies** [comment]
Ah thanks for the quick response. Yes, I just tried to run the container as standalone. Could you point me to a tutorial showing how to integrate this container into Galaxy?

Thanks,
Christoph

**Comment by bgruening** [comment]
@c-ruttkies look at this: https://docs.galaxyproject.org/en/master/admin/interactive_environments.html
Also have a look at the workshop material from last year: https://gcc16.sched.com/event/5Y5e/introduction-to-galaxy-interactive-environments

ping @blankclemens

**Comment by hexylena** [comment]
The python error is due to missing `CORS_ORIGIN` environment variable. If you set that, that error will go away.

**Comment by c-ruttkies** [comment]
Thanks for the comments! I got it running via Galaxy now.

**Comment by bgruening** [comment]
Great news!
