### ISSUE TITLE
Not able to retrieve kernelspecs

### ISSUE THREAD

**Issue by afgane** [bgruening/docker-jupyter-notebook#24]
Move this out of our chat @bgruening as I dug a bit deeper but feeling stuck.
The overall issue is that this image gets loaded as a Galaxy IE and Jupyter starts but it does not load any kernels. This seems to be caused by not being able to retrieve kernelspecs (e.g., `<galaxy_host>/galaxy/gie_proxy/jupyter/ipython/api/kernelspecs`). 
Connecting to a running container, the kernels are available:
```
$ jupyter kernelspec list
Available kernels:
  ruby         /home/jovyan/.ipython/kernels/ruby
  bash         /home/jovyan/.local/share/jupyter/kernels/bash
  ir           /opt/conda/share/jupyter/kernels/ir
  julia-0.5    /opt/conda/share/jupyter/kernels/julia-0.5
  python3      /opt/conda/share/jupyter/kernels/python3
  python2      /usr/local/share/jupyter/kernels/python2
```
The container log just records 404 on the above URL but nothing more: https://gist.github.com/afgane/7297b8964abd2c88136282b282a0b842

All of this is from Ubuntu 16.04, Galaxy 17.09 now, and Docker 17.05.0-ce using 17.09 version of the IE image. I've been seeing the same behavior on Ubuntu 14.04 and Galaxy 17.05 over the past day.

On the other hand, usegalaxy.org returns a json with the specs (after loading an IE visit https://usegalaxy.org/gie_proxy/jupyter/ipython/api/kernelspecs). 

Not sure where else to look so if you have any pointers or would like access to this instance, let me know.

**Comment by natefoo** [comment]
@afgane check out [this proxy rule](https://github.com/galaxyproject/usegalaxy-playbook/blob/98aeb5b7d8689e9fff6e2b2b3793235e0b7d1ab8/env/main/templates/nginx/usegalaxy.j2#L170) and see if it works for you.

**Comment by afgane** [comment]
Thanks but I had that rule in place and no go. Even if I omit nginx from the equation and try to `curl` the container directly from the host (e.g., `curl localhost:32769/galaxy/gie_proxy/jupyter/ipython/kernelspecs`), I still get 404 so it seems there's a disconnect between the container and the host node proxy? I'm really not sure how this works at that level. Is there a way to query that endpoint from within the container? I guess it's Jupyter that exposes that endpoint from within the container?

**Comment by natefoo** [comment]
Can you tell if the 404 is from nginx or Jupyter?

~~The unproxied URL should be `localhost:32769/jupyter/ipython/api/kernelspecs` I believe.~~ Nevermind

**Comment by natefoo** [comment]
Also, enable `rewrite_log` in nginx.conf

**Comment by afgane** [comment]
The way I understand this, the 404 is coming from Jupyter. The container log shows the following, which to me implies it's not an nginx routing issue: 
```
$ docker logs 06363a2d44ac
[TrustNotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
Signing notebook: /import/ipython_galaxy_notebook.ipynb
[W 15:35:26.880 NotebookApp] Config option `profile` not recognized by `NotebookApp`.  Did you mean `certfile`?
[I 15:35:26.886 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 15:35:27.437 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 15:35:27.452 NotebookApp] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.5/site-packages/jupyterlab
[I 15:35:27.458 NotebookApp] Serving notebooks from local directory: /import
[I 15:35:27.458 NotebookApp] 0 active kernels
[I 15:35:27.458 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/gie_proxy/jupyter/ipython/
[I 15:35:27.458 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:35:28.008 NotebookApp] 302 GET /gie_proxy/jupyter/ipython/login?next=%2Fgie_proxy%2Fjupyter%2Fipython%2Ftree (172.17.0.1) 1.75ms
[W 15:35:28.658 NotebookApp] 404 GET /gie_proxy/ipython/api/kernelspecs (172.17.0.1) 7.28ms referer=http://54.197.115.156/gie_proxy/jupyter/ipython/notebooks/ipython_galaxy_notebook.ipynb
[W 15:35:30.476 NotebookApp] 404 GET /gie_proxy/jupyter/ipython/static/components/preact/preact.min.js.map (172.17.0.1) 2.40ms referer=None
[W 15:35:30.479 NotebookApp] 404 GET /gie_proxy/jupyter/ipython/static/components/proptypes/index.js.map (172.17.0.1) 1.60ms referer=None
[W 15:35:30.481 NotebookApp] 404 GET /gie_proxy/jupyter/ipython/static/components/preact-compat/preact-compat.min.js.map (172.17.0.1) 1.42ms referer=None
```

**Comment by natefoo** [comment]
This looks wrong, shouldn't it be `/gie_proxy/jupyter/ipython/api/kernelspecs`?:

```
[W 15:35:28.658 NotebookApp] 404 GET /gie_proxy/ipython/api/kernelspecs (172.17.0.1) 7.28ms referer=http://54.197.115.156/gie_proxy/jupyter/ipython/notebooks/ipython_galaxy_notebook.ipynb
```

What is your `proxy_pass` for the `location` that does this proxying?

**Comment by afgane** [comment]
Ahh - yes - that did it. That second pair of eyes... Thanks!
