### ISSUE TITLE
iHaskell Kernel is not available

### ISSUE THREAD

**Issue by frostyandy2k** [bgruening/docker-jupyter-notebook#33]
What I did:

`docker pull bgruening/docker-jupyter-notebook`

`docker run --rm -it -p 8889:8888 bgruening/docker-jupyter-notebook`

Result (see image):
No iHaskell Kernel available

![image](https://user-images.githubusercontent.com/1107113/65511616-46994080-dee0-11e9-92f0-7272ecb85aba.png)

**Comment by bgruening** [comment]
Mh, I was not aware people acutally using this. If you are still interested I will add it back.

Have you tried live.usegalaxy.eu?

**Comment by bgruening** [comment]
I release a new version without ihaskell, please let me now if this is still a usecase and I will try to add it back. We might need to work on a recent conda package for that Kernel.
