### ISSUE TITLE
Kernel: Octave

### ISSUE THREAD

**Issue by hexylena** [bgruening/docker-jupyter-notebook#4]
https://github.com/calysto/octave_kernel

we might want to add something like this. Thinking of @gregvonkuster's engineering users, a matlab-compatible GIE might be of interest? Dunno.

**Comment by bgruening** [comment]
I'm more in favour of maintaining on IE that supports as many kernels as possible. I feel swamp with all the maintenance right now.

I will try to get octave in, seems to be easy enough.

**Comment by hexylena** [comment]
@bgruening that was the intention. One IE, another kernel. No rush, you don't need to do it yourself, it was just an issue to see if a) anyone had interest, b) anyone had time to do it. I don't have a pressing need for this.

**Comment by bgruening** [comment]
Awesome! I get this going.
